Update fixtures and introduces new parameter in items_fetch
brazil-data-cube/rstac pull request #39
Opened 2021-06-21 17:56 UTC by OldLipe

- Add the `path_row` parameter to give more flexibility in paging different STACs.

2021-06-23 15:58 UTC, rolfsimoes commented on R/documents.R
> +#' @param matched_field   a \code{character} vector with a path with the path
"with the path"

2021-06-23 16:01 UTC, rolfsimoes requested changes

2021-06-23 16:21 UTC, OldLipe commented on R/documents.R
> +      matched <- sapply(list(items), `[[`, matched_field)
Done. Thanks!

2021-06-23 16:23 UTC, OldLipe reviewed
The review issues was done!

2021-06-23 16:23 UTC, rolfsimoes approved these changes

2021-06-25 12:43 UTC, gqueiroz approved these changes

2021-06-25 12:43 UTC, merged